//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _222_Notice_Sabancheev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int CityID { get; set; }
        public int UserID { get; set; }
        public int CategoryID { get; set; }
        public bool Status { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Coast { get; set; }
        public int TypeID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        public virtual Type Type { get; set; }
        public virtual User User { get; set; }
    }
}
